# Generated by Django 5.1.4 on 2026-07-11 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_ticket_creador_ticket_fecha_vencimiento_sla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impacto', models.IntegerField(choices=[(1, 'Hospital / Alta Críticidad'), (2, 'Servicio / Área'), (3, 'Paciente / Usuario Único'), (4, 'Bajo / Sin Impacto Clínico')], verbose_name='Impacto')),
                ('urgencia', models.IntegerField(choices=[(1, 'Alta / Detiene Operación'), (2, 'Media / Operación Degradada'), (3, 'Baja / Operación Normal')], verbose_name='Urgencia')),
                ('tiempo_respuesta_minutos', models.IntegerField(default=15, verbose_name='SLA Primera Respuesta (min)')),
                ('tiempo_resolucion_horas', models.IntegerField(default=24, verbose_name='SLA Resolución (horas)')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.prioridad', verbose_name='Prioridad Resultante')),
            ],
            options={
                'verbose_name': 'Matriz SLA',
                'verbose_name_plural': 'Matrices SLA',
                'unique_together': {('impacto', 'urgencia')},
            },
        ),
    ]
