# Generated by Django 5.1.4 on 2026-07-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Conocimiento',
                'verbose_name_plural': 'Categorías de Conocimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Síntoma Breve')),
                ('sintomas', models.TextField(verbose_name='Síntomas Detallados')),
                ('solucion', models.TextField(verbose_name='Solución o Procedimiento')),
                ('es_error_conocido', models.BooleanField(default=True, verbose_name='Es Error Conocido')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='conocimiento.categoriaconocimiento')),
            ],
            options={
                'verbose_name': 'Artículo de Conocimiento',
                'verbose_name_plural': 'Artículos de Conocimiento',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
