# Generated by Django 6.0.6 on 2026-07-09 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código del Acta')),
                ('receptor_nombre', models.CharField(max_length=100, verbose_name='Nombre del Receptor')),
                ('receptor_rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT del Receptor')),
                ('receptor_cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Receptor')),
                ('receptor_unidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad del Receptor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Acta')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='actas/pdf/', verbose_name='PDF generado')),
                ('pdf_firmado', models.FileField(blank=True, null=True, upload_to='actas/firmadas/', verbose_name='PDF firmado')),
                ('firma_receptor', models.ImageField(blank=True, null=True, upload_to='actas/firmas/', verbose_name='Firma del Receptor')),
                ('firma_encargado', models.ImageField(blank=True, null=True, upload_to='actas/firmas/', verbose_name='Firma del Encargado')),
                ('timbre_encargado', models.ImageField(blank=True, null=True, upload_to='actas/timbres/', verbose_name='Timbre del Encargado')),
                ('email_receptor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Receptor')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('enviado', 'Enviado')], db_index=True, default='emitido', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Encargado TIC')),
            ],
            options={
                'verbose_name': 'Acta de Entrega',
                'verbose_name_plural': 'Actas de Entrega',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ActaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('EQUIPO', 'Equipo'), ('ANEXO', 'Anexo')], max_length=20, verbose_name='Tipo de Ítem')),
                ('id_item', models.PositiveIntegerField(help_text='ID del Equipo o Anexo según tipo_item', verbose_name='ID del Ítem')),
                ('articulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artículo')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('pma_lugar', models.CharField(blank=True, max_length=255, null=True, verbose_name='PMA / Lugar')),
                ('estado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado del ítem')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='actas.acta', verbose_name='Acta')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_detalles', to='mantenedores.edificio', verbose_name='Edificio')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_detalles', to='mantenedores.piso', verbose_name='Piso')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_detalles', to='mantenedores.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Detalle de Acta',
                'verbose_name_plural': 'Detalles de Acta',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['estado'], name='idx_acta_estado'),
        ),
        migrations.AddIndex(
            model_name='acta',
            index=models.Index(fields=['fecha'], name='idx_acta_fecha'),
        ),
        migrations.AddIndex(
            model_name='actadetalle',
            index=models.Index(fields=['tipo_item', 'id_item'], name='idx_actadetalle_tipo_item'),
        ),
    ]
