# Generated by Django 6.0.6 on 2026-07-09 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('permisos', models.JSONField(default=dict, help_text='Diccionario de 19 permisos booleanos', verbose_name='Permisos (JSON)')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('creado_por', models.CharField(blank=True, max_length=120, null=True, verbose_name='Creado por')),
                ('actualizado_por', models.CharField(blank=True, max_length=120, null=True, verbose_name='Actualizado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Usuario')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('LOGIN_OK', 'Inicio Sesión Exitoso'), ('LOGIN_FAIL', 'Inicio Sesión Fallido'), ('LOGOUT', 'Cierre de Sesión')], db_index=True, max_length=10, verbose_name='Acción')),
                ('tabla', models.CharField(db_index=True, max_length=100, verbose_name='Tabla/Objeto')),
                ('registro_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID de Registro')),
                ('detalles', models.TextField(verbose_name='Detalles de la Operación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['tabla', 'registro_id'], name='idx_log_tabla_reg'), models.Index(fields=['ip_address'], name='idx_log_ip')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad / Servicio')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('grado', models.CharField(max_length=20, verbose_name='Grado')),
                ('rut', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='RUT del Funcionario')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.rol', verbose_name='Rol TIC')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
