# Generated by Django 5.1.4 on 2026-07-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario'),
        ('mantenedores', '0004_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo Antiguo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='mantenedores.cargo', verbose_name='Cargo / Rol'),
        ),
    ]
