# Generated by Django 5.1.4 on 2026-07-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionario_cargo_old_alter_funcionario_cargo'),
        ('mantenedores', '0004_cargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Log de AuditorÃ\xada', 'verbose_name_plural': 'Logs de AuditorÃ\xada'},
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='mantenedores.cargo', verbose_name='Cargo / Rol'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='mantenedores.unidad', verbose_name='Unidad / Servicio'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'CreaciÃ³n'), ('MODIFICAR', 'ModificaciÃ³n'), ('ELIMINAR', 'EliminaciÃ³n'), ('LOGIN_OK', 'Inicio SesiÃ³n Exitoso'), ('LOGIN_FAIL', 'Inicio SesiÃ³n Fallido'), ('LOGOUT', 'Cierre de SesiÃ³n')], db_index=True, max_length=10, verbose_name='AcciÃ³n'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='detalles',
            field=models.TextField(verbose_name='Detalles de la OperaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='DirecciÃ³n IP'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.rol', verbose_name='Rol TIC'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TelÃ©fono'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DescripciÃ³n'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de ActualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de CreaciÃ³n'),
        ),
    ]
