# Generated by Django 5.1.4 on 2026-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logauditoria_options_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='icono',
            field=models.CharField(blank=True, default='ms-Icon--Contact', max_length=50, null=True, verbose_name='Icono Fluent UI'),
        ),
    ]
