# Generated by Django 5.1.4 on 2026-07-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rol_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Rol de Sistema (No borrable)'),
        ),
    ]
