# Generated by Django 5.1.4 on 2026-08-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rol_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('LOGIN_OK', 'Inicio Sesión Exitoso'), ('LOGIN_FAIL', 'Inicio Sesión Fallido'), ('LOGOUT', 'Cierre de Sesión')], db_index=True, max_length=10, verbose_name='AcciÃ³n'),
        ),
    ]
