# Generated by Django 6.0.6 on 2026-07-09 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('propietario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Propietario')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Credencial de Correo',
                'verbose_name_plural': 'Credenciales de Correo',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del Grupo')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Grupo de Correo',
                'verbose_name_plural': 'Grupos de Correo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiembroGrupoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='correos.grupocorreo', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupos',
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'email'), name='uniq_miembro_grupo_email')],
            },
        ),
    ]
