# Generated by Django 5.1.4 on 2026-07-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.office365.com', max_length=150, verbose_name='Servidor SMTP (Host)')),
                ('puerto', models.IntegerField(default=587, verbose_name='Puerto')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario / Email')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('remitente_por_defecto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Remitente por Defecto (From)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SMTP',
                'verbose_name_plural': 'Configuraciones SMTP',
            },
        ),
    ]
