# Generated by Django 5.1.4 on 2026-08-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0002_configuracionsmtp'),
        ('tickets', '0010_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación de Ticket'), ('RESOLUCION', 'Resolución de Ticket'), ('ASIGNACION', 'Asignación de Ticket'), ('PAUSA', 'Ticket Pausado'), ('REACTIVACION', 'Ticket Reactivado'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de Notificación')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Destinatario')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('estado', models.CharField(choices=[('SIN_SMTP', 'Sin SMTP Configurado'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('error_detalle', models.TextField(blank=True, default='', verbose_name='Detalle del Error')),
                ('reenviado_manualmente', models.BooleanField(default=False, verbose_name='Reenviado Manualmente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True, verbose_name='Último Intento')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correo_logs', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Log de Correo',
                'verbose_name_plural': 'Logs de Correo',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='correos_cor_estado_41c840_idx'), models.Index(fields=['ticket'], name='correos_cor_ticket__551fd6_idx')],
            },
        ),
    ]
