# Generated by Django 5.1.4 on 2026-08-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correos', '0003_correolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsmtp',
            name='nombre_sistema',
            field=models.CharField(default='TicSystem Mesa de Ayuda', help_text='Texto que aparecerá en el encabezado azul de todos los correos.', max_length=150, verbose_name='Nombre del Sistema (Encabezado del Correo)'),
        ),
        migrations.AddField(
            model_name='configuracionsmtp',
            name='pie_correo',
            field=models.CharField(default='Mesa de Ayuda - Plataforma Tecnológica', help_text='Texto institucional que aparecerá al pie de todos los correos.', max_length=200, verbose_name='Pie de Correo (Footer)'),
        ),
    ]
