# Generated by Django 6.0.6 on 2026-07-09 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaHospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Área')),
            ],
            options={
                'verbose_name': 'Área Hospitalaria',
                'verbose_name_plural': 'Áreas Hospitalarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre del Artículo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre del Estado')),
                ('color_hex', models.CharField(default='#17a2b8', max_length=20, verbose_name='Color (hex) para badges')),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Modelo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modelos_anexos/', verbose_name='Imagen del Modelo')),
            ],
            options={
                'verbose_name': 'Modelo de Anexo',
                'verbose_name_plural': 'Modelos de Anexos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre del Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre del SO')),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistemas Operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la VLAN')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del Edificio')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edificios', to='mantenedores.institucion', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Modelo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modelos/', verbose_name='Imagen del Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='mantenedores.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['marca__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Piso')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias del Piso')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos', to='mantenedores.edificio', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Piso',
                'verbose_name_plural': 'Pisos',
                'ordering': ['edificio__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Recinto')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='mantenedores.piso', verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Código PMA')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmas', to='mantenedores.recinto', verbose_name='Recinto')),
            ],
            options={
                'verbose_name': 'PMA',
                'verbose_name_plural': 'PMAs',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Sector')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='mantenedores.piso', verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='recinto',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='mantenedores.sector', verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Unidad')),
                ('area_hospitalaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='mantenedores.areahospitalaria', verbose_name='Área Hospitalaria')),
            ],
            options={
                'verbose_name': 'Unidad / Servicio',
                'verbose_name_plural': 'Unidades / Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='recinto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='mantenedores.unidad', verbose_name='Unidad / Servicio'),
        ),
        migrations.AddConstraint(
            model_name='edificio',
            constraint=models.UniqueConstraint(fields=('nombre', 'institucion'), name='uniq_edificio_nombre_institucion'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='uniq_modelo_marca_nombre'),
        ),
        migrations.AddConstraint(
            model_name='piso',
            constraint=models.UniqueConstraint(fields=('edificio', 'nombre'), name='uniq_piso_edificio_nombre'),
        ),
    ]
