# Generated by Django 6.0.6 on 2026-07-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT Empresa'),
        ),
    ]
