# Generated by Django 5.1.4 on 2026-07-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0002_proveedor_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/', verbose_name='Imagen por Defecto'),
        ),
    ]
