# Generated by Django 5.1.4 on 2026-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0003_articulo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
    ]
