# Generated by Django 5.1.4 on 2026-07-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0004_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pisos', to='mantenedores.edificio', verbose_name='Edificio'),
        ),
        migrations.AlterField(
            model_name='pma',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pmas', to='mantenedores.recinto', verbose_name='Recinto'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='piso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recintos', to='mantenedores.piso', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recintos', to='mantenedores.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recintos', to='mantenedores.unidad', verbose_name='Unidad / Servicio'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='piso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectores', to='mantenedores.piso', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='area_hospitalaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='mantenedores.areahospitalaria', verbose_name='Área Hospitalaria'),
        ),
    ]
