# Generated by Django 5.1.4 on 2026-07-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0005_alter_piso_edificio_alter_pma_recinto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloanexo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modelos_anexos', to='mantenedores.marca', verbose_name='Marca del Modelo'),
        ),
    ]
