# Generated by Django 6.0.6 on 2026-07-09 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/', verbose_name='Imagen del Equipo')),
                ('correlativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correlativo')),
                ('orden_interno', models.IntegerField(blank=True, null=True, verbose_name='Orden Interno')),
                ('serie_corta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie Equipo (Corta)')),
                ('estado_candado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Candado/Observación')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('anexo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo telefónico')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario asignado')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='Office')),
                ('activador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Activador / Cuenta')),
                ('pmalugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='PMA / Lugar')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.articulo', verbose_name='Artículo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.estadoequipo', verbose_name='Estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.modelo', verbose_name='Modelo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.pma', verbose_name='PMA (Punto de Montaje)')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.proveedor', verbose_name='Proveedor')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='mantenedores.sistemaoperativo', verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de Mantención')),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Fecha en que el equipo fue devuelto al usuario tras atención', null=True, verbose_name='Fecha de Devolución')),
                ('solicitante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Solicitante')),
                ('falla_reportada', models.TextField(blank=True, null=True, verbose_name='Falla Reportada')),
                ('actividades_realizadas', models.TextField(blank=True, null=True, verbose_name='Actividades Realizadas')),
                ('servicio_unidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio / Unidad')),
                ('tipo_registro', models.CharField(choices=[('MANTENCION', 'Mantención'), ('REPARACION_EXTERNA', 'Reparación Externa'), ('MOVIMIENTO', 'Movimiento'), ('ACTUALIZACION_SISTEMA', 'Actualización de Sistema'), ('REEMPLAZO', 'Reemplazo'), ('REVISION_PREVENTIVA', 'Revisión Preventiva')], default='MANTENCION', max_length=30, verbose_name='Tipo de Registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bitacoras_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Registros de Bitácora',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FALLA', 'Falla'), ('ACTIVIDAD', 'Actividad')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(db_index=True, default=10, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_opciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Opción de Bitácora',
                'verbose_name_plural': 'Opciones de Bitácora',
                'ordering': ['tipo', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nombre'), name='uniq_bitacora_opcion_tipo_nombre')],
            },
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['serial_number'], name='equipos_equ_serial__26fea4_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado'], name='equipos_equ_estado__598d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['pma'], name='idx_equipo_pma'),
        ),
        migrations.AddIndex(
            model_name='bitacoraequipo',
            index=models.Index(fields=['equipo'], name='idx_bitacora_equipo'),
        ),
        migrations.AddIndex(
            model_name='bitacoraequipo',
            index=models.Index(fields=['tecnico'], name='idx_bitacora_tecnico'),
        ),
        migrations.AddIndex(
            model_name='bitacoraequipo',
            index=models.Index(fields=['tipo_registro'], name='idx_bitacora_tipo'),
        ),
    ]
