# Generated by Django 5.1.4 on 2026-07-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraequipo',
            name='tipo_registro',
            field=models.CharField(choices=[('MANTENCION', 'Mantención'), ('REPARACION_EXTERNA', 'Reparación Externa'), ('MOVIMIENTO', 'Movimiento'), ('ACTUALIZACION_SISTEMA', 'Actualización de Sistema'), ('REEMPLAZO', 'Reemplazo'), ('REVISION_PREVENTIVA', 'Revisión Preventiva'), ('INSTALACION', 'Instalación'), ('TRASLADO', 'Traslado'), ('AISLAMIENTO_MINSAL', 'Aislamiento MINSAL')], default='MANTENCION', max_length=30, verbose_name='Tipo de Registro'),
        ),
    ]
