# Generated by Django 5.1.4 on 2026-07-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logauditoria_options_alter_funcionario_cargo_and_more'),
        ('equipos', '0002_alter_bitacoraequipo_tipo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraequipo',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_solicitadas', to='core.funcionario', verbose_name='Solicitante'),
        ),
    ]
