# Generated by Django 5.1.4 on 2026-07-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_bitacoraequipo_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraequipo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el equipo fue devuelto al usuario tras atención', null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='bitacoraequipo',
            name='fecha_mantenimiento',
            field=models.DateTimeField(verbose_name='Fecha de Mantención'),
        ),
    ]
