# Generated by Django 5.1.4 on 2026-07-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_alter_bitacoraequipo_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='patch_panel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Patch Panel'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puerto_red',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puerto / Boca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='switch_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Switch (Nombre/IP)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='vencimiento_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Garantía'),
        ),
    ]
