# Generated by Django 5.1.4 on 2026-07-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_equipo_fecha_compra_equipo_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='num_inventario',
            field=models.CharField(blank=True, db_index=True, help_text='Número de Activo Fijo asignado por Contabilidad (Ej: AF-000345)', max_length=80, null=True, unique=True, verbose_name='N° Inventario Institucional'),
        ),
    ]
