# Generated by Django 6.0.6 on 2026-06-25 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('LOGIN_OK', 'Inicio Sesión Exitoso'), ('LOGIN_FAIL', 'Inicio Sesión Fallido'), ('LOGOUT', 'Cierre de Sesión')], max_length=10, verbose_name='Acción')),
                ('tabla', models.CharField(max_length=100, verbose_name='Tabla/Objeto')),
                ('registro_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Registro')),
                ('detalles', models.TextField(verbose_name='Detalles de la Operación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad / Servicio')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('grado', models.CharField(max_length=20, verbose_name='Grado')),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='RUT del Funcionario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
