# Generated by Django 6.0.6 on 2026-07-09 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nivel')),
                ('sla_respuesta_minutos', models.IntegerField(help_text='Tiempo esperado para tomar el caso', verbose_name='SLA respuesta (minutos)')),
                ('sla_resolucion_horas', models.IntegerField(help_text='Tiempo esperado para solucionar', verbose_name='SLA resolución (horas)')),
                ('color_hex', models.CharField(default='#333333', max_length=20, verbose_name='Color (hex)')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('solicitante_nombre', models.CharField(max_length=255, verbose_name='Nombre del Solicitante')),
                ('solicitante_rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT del Solicitante')),
                ('solicitante_correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Solicitante')),
                ('solicitante_anexo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo del Solicitante')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('grupo_asignado', models.IntegerField(blank=True, null=True, verbose_name='Grupo asignado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TERRENO', 'En Terreno'), ('RESUELTO', 'Resuelto')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('fecha_toma', models.DateTimeField(blank=True, help_text='El segundo exacto en que el técnico asume', null=True, verbose_name='Fecha de Toma')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.categoria', verbose_name='Categoría')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='mantenedores.edificio', verbose_name='Edificio')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='equipos.equipo', verbose_name='Equipo')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenedores.piso', verbose_name='Piso')),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.prioridad', verbose_name='Prioridad')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='mantenedores.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='TicketBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('tipo_nota', models.CharField(choices=[('PUBLICA', 'Pública'), ('INTERNA', 'Interna'), ('SISTEMA', 'Sistema')], default='INTERNA', max_length=20, verbose_name='Tipo de nota')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tickets.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota de Ticket',
                'verbose_name_plural': 'Notas de Tickets',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='idx_ticket_estado'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tecnico'], name='idx_ticket_tecnico'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='idx_ticket_prioridad'),
        ),
    ]
