# Generated by Django 5.1.4 on 2026-07-11 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creador (Operador)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_vencimiento_sla',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento SLA Resolución'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='impacto',
            field=models.IntegerField(choices=[(1, 'Hospital / Alta Críticidad'), (2, 'Servicio / Área'), (3, 'Paciente / Usuario Único'), (4, 'Bajo / Sin Impacto Clínico')], default=4, verbose_name='Impacto'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('INCIDENTE', 'Incidente (Falla/Interrupción)'), ('REQUERIMIENTO', 'Requerimiento (Solicitud)')], default='INCIDENTE', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgencia',
            field=models.IntegerField(choices=[(1, 'Alta / Detiene Operación'), (2, 'Media / Operación Degradada'), (3, 'Baja / Operación Normal')], default=3, verbose_name='Urgencia'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Problema'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico Técnico'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En Proceso'), ('ESPERA_APROBACION', 'En Espera de Aprobación'), ('PENDIENTE_USUARIO', 'Pendiente Usuario'), ('PENDIENTE_PROVEEDOR', 'Pendiente Proveedor'), ('ESCALADO', 'Escalado'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, null=True, verbose_name='Solución Aplicada'),
        ),
    ]
