# Generated by Django 5.1.4 on 2026-07-11 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_creador_ticket_fecha_vencimiento_sla_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoResolutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('miembros', models.ManyToManyField(blank=True, related_name='grupos_resolutores', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos Miembros')),
            ],
            options={
                'verbose_name': 'Grupo Resolutor',
                'verbose_name_plural': 'Grupos Resolutores',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo_resolutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.gruporesolutor', verbose_name='Grupo de Resolución Asignado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='grupo_resolutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asignados', to='tickets.gruporesolutor', verbose_name='Grupo Resolutor'),
        ),
    ]
