# Generated by Django 5.1.4 on 2026-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_gruporesolutor_categoria_grupo_resolutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='anexo_contacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo/Teléfono de Contacto'),
        ),
    ]
