# Generated by Django 5.1.4 on 2026-07-11 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionario'),
        ('tickets', '0004_ticket_anexo_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_solicitados', to='core.funcionario', verbose_name='Solicitante'),
        ),
    ]
