# Generated by Django 5.1.4 on 2026-07-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_categoria_grupo_resolutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo de Contacto'),
        ),
    ]
