# Generated by Django 5.1.4 on 2026-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_correo_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruporesolutor',
            name='icono',
            field=models.CharField(blank=True, default='ms-Icon--Group', max_length=50, null=True, verbose_name='Icono Fluent UI'),
        ),
    ]
