# Generated by Django 5.1.4 on 2026-07-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_gruporesolutor_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruporesolutor',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Grupo de Sistema (No borrable)'),
        ),
    ]
