# Generated by Django 6.0.6 on 2026-07-09 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('horas_objetivo', models.IntegerField(default=48, verbose_name='Horas objetivo')),
                ('alerta_porcentaje', models.IntegerField(default=80, verbose_name='% alerta')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código PMA')),
                ('estado', models.CharField(default='Activo', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('edificio_piso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pmas', to='mantenedores.piso', verbose_name='Edificio / Piso')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmas', to='mantenedores.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'PMA',
                'verbose_name_plural': 'PMAs',
                'ordering': ['codigo', 'edificio_piso'],
            },
        ),
        migrations.CreateModel(
            name='InfraestructuraRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_direccion', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='Dirección IP')),
                ('switch_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del Switch')),
                ('switch_port', models.CharField(blank=True, max_length=20, null=True, verbose_name='Puerto del Switch')),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('FALLA', 'Falla')], db_index=True, default='LIBRE', max_length=20, verbose_name='Estado')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('mac', models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC')),
                ('rack', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rack')),
                ('patch_panel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patch Panel')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_red', to='mantenedores.edificio', verbose_name='Edificio')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips_red', to='mantenedores.institucion', verbose_name='Institución')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_red', to='mantenedores.piso', verbose_name='Piso')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips_red', to='mantenedores.unidad', verbose_name='Unidad')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='mantenedores.vlan', verbose_name='VLAN')),
                ('pma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='redes.pma', verbose_name='PMA')),
            ],
            options={
                'verbose_name': 'IP de Red',
                'verbose_name_plural': 'IPs de Red (IPAM)',
                'ordering': ['ip_direccion'],
            },
        ),
        migrations.CreateModel(
            name='RangoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=200, verbose_name='Unidad')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('pma', models.CharField(max_length=100, verbose_name='PMA')),
                ('rack', models.CharField(max_length=100, verbose_name='Rack')),
                ('dato', models.CharField(max_length=100, verbose_name='Dato (último octeto)')),
                ('rango', models.CharField(max_length=50, verbose_name='Rango (3 primeros octetos)')),
                ('ip', models.GenericIPAddressField(verbose_name='IP completa')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado (ocupado)')),
                ('comentario', models.TextField(default='', verbose_name='Comentario')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos_ip', to='mantenedores.piso', verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Rango de IP',
                'verbose_name_plural': 'Rangos de IP por Piso',
                'ordering': ['piso', 'rango', 'ip'],
            },
        ),
        migrations.AddConstraint(
            model_name='pma',
            constraint=models.UniqueConstraint(fields=('codigo', 'edificio_piso'), name='uniq_pma_codigo_piso'),
        ),
        migrations.AddIndex(
            model_name='infraestructurared',
            index=models.Index(fields=['estado'], name='idx_ipred_estado'),
        ),
        migrations.AddIndex(
            model_name='infraestructurared',
            index=models.Index(fields=['pma'], name='idx_ipred_pma'),
        ),
        migrations.AddIndex(
            model_name='rangoip',
            index=models.Index(fields=['piso'], name='idx_rangoip_piso'),
        ),
        migrations.AddIndex(
            model_name='rangoip',
            index=models.Index(fields=['ip'], name='idx_rangoip_ip'),
        ),
    ]
