# Generated by Django 6.0.6 on 2026-07-09 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anexo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Anexo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca (texto)')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo (texto)')),
                ('pma_lugar', models.CharField(max_length=100, verbose_name='PMA / Lugar')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_index=True, default='Activo', max_length=20, verbose_name='Estado')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Número de Serie')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anexos/', verbose_name='Foto')),
                ('grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='mantenedores.edificio', verbose_name='Edificio')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='mantenedores.institucion', verbose_name='Establecimiento')),
                ('modelo_anexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='mantenedores.modeloanexo', verbose_name='Modelo (catálogo)')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='mantenedores.piso', verbose_name='Piso')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='mantenedores.proveedor', verbose_name='Proveedor')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='mantenedores.unidad', verbose_name='Unidad / Servicio')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['numero_anexo'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('sub_requerimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Requerimiento')),
                ('accion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acción')),
                ('nombre_usuario_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Usuario Requerimiento')),
                ('ubicacion_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Requerimiento')),
                ('estado_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Requerimiento')),
                ('grupo_captura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo Captura')),
                ('cambiar_dos_anexos', models.BooleanField(default=False, verbose_name='Cambiar dos anexos')),
                ('numero_anexo_cambio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de anexo a cambiar')),
                ('cascada', models.BooleanField(default=False, verbose_name='Cascada')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del requerimiento')),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='anexos.anexo', verbose_name='Anexo')),
            ],
            options={
                'verbose_name': 'Requerimiento de Cambio',
                'verbose_name_plural': 'Requerimientos de Cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['numero_anexo'], name='idx_anexo_numero'),
        ),
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['estado'], name='idx_anexo_estado'),
        ),
        migrations.AddIndex(
            model_name='anexo',
            index=models.Index(fields=['edificio'], name='idx_anexo_edificio'),
        ),
    ]
