# Generated by Django 5.1.4 on 2026-07-15 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0001_initial'),
        ('mantenedores', '0006_modeloanexo_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='pma_lugar',
        ),
        migrations.AddField(
            model_name='anexo',
            name='pma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='mantenedores.pma', verbose_name='PMA (Punto de Montaje)'),
        ),
    ]
