# Generated by Django 5.1.4 on 2026-07-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0002_remove_anexo_pma_lugar_anexo_pma'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='numero_inventario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Inventario'),
        ),
    ]
