# Generated by Django 6.0.6 on 2026-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyudaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Ayuda Rápida',
                'verbose_name_plural': 'Ayudas Rápidas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Tarea')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Ítem de Checklist',
                'verbose_name_plural': 'Ítems de Checklist',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('link', models.CharField(default='#', max_length=255, verbose_name='Link')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('icono', models.CharField(default='bi bi-link-45deg', max_length=100, verbose_name='Icono (clase Bootstrap Icons)')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(db_index=True, default=0, verbose_name='Orden')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Web App / Acceso',
                'verbose_name_plural': 'Web Apps / Accesos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
